"""
`quality/adversarial/disclosure-shapes.yaml`'s structure, held to the claims its
own header makes.

The header says each pair differs only in its last sentence, that the allow half
echoes the platform's disclosure verbatim, that one block sentence carries the
rule's own negation example verbatim, and that every row declares what
`topic_baseline.py`'s coverage check needs. A corpus that says those things and
does not hold them is a measurement of something else, and nothing would notice.

This asserts nothing about what any guardrail does with the rows: only a sweep can.

Hermetic (G8): reads committed files. Owning seats: Security (the corpus) · AI
Quality · Platform Engineering.
"""
from __future__ import annotations

import pathlib
import re

import pytest
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
CORPUS_PATH = ROOT / "quality" / "adversarial" / "disclosure-shapes.yaml"
CORPUS = yaml.safe_load(CORPUS_PATH.read_text(encoding="utf-8"))
PAIRS = CORPUS["pairs"]
CONTROLS = CORPUS["controls"]
DISCLOSURE = "This copy was generated by AI."
NEGATION = "written by a human, not by AI"
#: The disclosure pack's accepted wordings, read from the pack rather than retyped.
PACK = ROOT / "services" / "highlights-agent" / "evals" / "disclosure" / "cases.yaml"


def _flat(text: str) -> str:
    return " ".join(text.split())


def _split_last_sentence(text: str) -> tuple[str, str]:
    copy, _, last = _flat(text).rpartition(". ")
    return copy, last


def test_the_frozen_declarations_are_present_and_name_what_they_predate():
    for key in ("frozen_at", "frozen_before", "judges"):
        assert CORPUS.get(key), f"disclosure-shapes.yaml declares no {key}"
    assert "candidate wording" in CORPUS["frozen_before"]
    assert CORPUS["source"] == "OUTPUT" and CORPUS["k"] == 3


def test_the_header_states_that_the_ordering_is_its_value():
    header = CORPUS_PATH.read_text(encoding="utf-8").split("\nversion:")[0]
    assert "ordering is the entire basis of its value" in header
    assert "stated weakness" in header


@pytest.mark.parametrize("pair", PAIRS, ids=[p["id"] for p in PAIRS])
def test_each_pair_differs_only_in_its_authorship_sentence(pair):
    block_copy, block_last = _split_last_sentence(pair["block"]["text"])
    allow_copy, allow_last = _split_last_sentence(pair["allow"]["text"])
    assert block_copy == allow_copy, f"{pair['id']}: the copy differs outside the last sentence"
    assert block_last != allow_last
    assert pair["block"]["expect"] == "blocked" and pair["allow"]["expect"] == "allowed"
    assert allow_last + ("" if allow_last.endswith(".") else ".") == DISCLOSURE or \
        _flat(pair["allow"]["text"]).endswith(DISCLOSURE)


def test_the_allow_sentence_is_the_platforms_own_disclosure_verbatim():
    source = (ROOT / "services" / "highlights-agent" / "gateway_client.py").read_text(encoding="utf-8")
    assert f'"{DISCLOSURE}"' in source, (
        "gateway_client.py no longer instructs this disclosure; the corpus's allow half "
        "now echoes a sentence the platform does not emit")
    for pair in PAIRS:
        assert _flat(pair["allow"]["text"]).endswith(DISCLOSURE), pair["id"]
    assert _flat(next(c for c in CONTROLS if c["id"] == "DSH-C04")["text"]) == DISCLOSURE


def test_the_anchor_carries_the_rules_negation_example_verbatim():
    rule = (ROOT / "rules" / "MER-AI-0001.yaml").read_text(encoding="utf-8")
    assert NEGATION in _flat(rule)
    anchor = next(p for p in PAIRS if p["id"] == "DSH-003")
    assert NEGATION in _flat(anchor["block"]["text"])


def test_the_second_disclosure_is_worded_from_the_packs_accepted_list():
    accepted = re.search(r"required: \[(.*?)\]", _flat(PACK.read_text(encoding="utf-8"))).group(1)
    phrases = [p.strip() for p in accepted.split(",")]
    text = _flat(next(c for c in CONTROLS if c["id"] == "DSH-C05")["text"])
    assert any(re.search(rf"\b{re.escape(p)}\b", text) for p in phrases if p != "AI")


def test_both_disjuncts_are_present():
    acts = {p["act"] for p in PAIRS}
    assert acts == {"denial", "affirmative"}


def test_every_row_has_a_unique_id_and_an_expectation():
    rows = [r for p in PAIRS for r in (p["block"], p["allow"])] + CONTROLS
    ids = [r["id"] for r in rows]
    assert len(ids) == len(set(ids)) == 17
    assert all(r["expect"] in ("blocked", "allowed") for r in rows)
    assert all(c["expect"] == "allowed" for c in CONTROLS)


def test_no_row_carries_entitlement_language():
    """The header's confound choice, held: a row that also names access could not
    say whether a block came from authorship or from the entitlement topics."""
    rows = [r for p in PAIRS for r in (p["block"], p["allow"])] + CONTROLS
    for row in rows:
        text = _flat(row["text"]).lower()
        for term in ("blackout", "entitle", "sports-tier", "subscription", "vpn", "market"):
            assert term not in text, f"{row['id']} carries {term!r}"
